// DO NOT EDIT THIS FILE ON YOUR OWN

import { createClient } from '@supabase/supabase-js';

const supabaseUrl = 'https://xynhhmliqdvyzrqnlvmk.supabase.co';
const supabaseAnonKey =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5bmhobWxpcWR2eXpycW5sdm1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI5MzAxMzMsImV4cCI6MjA0ODUwNjEzM30.9CQJDsQNph80lCbckTf5lCCaTf5tSLLvonHx21WTIqw';

export const supabase = createClient(supabaseUrl, supabaseAnonKey);

// Add error handling
supabase.handleError = (error) => {
  console.error('Supabase error:', error);
};

// Test the connection
export const testConnection = async () => {
  try {
    const { data, error } = await supabase.from('places').select('count');
    if (error) throw error;
    console.log('Supabase connected successfully');
    return true;
  } catch (error) {
    console.error('Failed to connect to Supabase:', error);
    return false;
  }
};

testConnection();
